import type { Metadata } from "next";
import { Rubik, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/navigation/Navbar";
import { ContextProvider } from "@/lib/context/AppContext";
import Sidebar from "@/components/navigation/Sidebar";
import PopupLayout from "@/components/popup/PopupLayout";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rubik.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <ContextProvider>
            <PopupLayout>
              <Navbar />
              <div className="flex flex-row">
                <Sidebar />
                {children}
              </div>
            </PopupLayout>
          </ContextProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
